# NumPy 

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

* Introduz objetos para matrizes e matrizes multidimensionais, bem como funções que permitem executar facilmente operações matemáticas e estatísticas avançadas nesses objetos
* Fornece vetorização de operações matemáticas em matrizes e matrizes, o que melhora significativamente o desempenho
* Muitas outras bibliotecas python são construídas no NumPy

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre por que você deseja usar Arrays em vez de listas, confira esta excelente publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

* Numpy array serão nossa principal ferramenta
* Numpy array essencialmente aparecem de duas formas: vetores e matrizes
* Vetores são de 1 dimensão e matrizes são de duas dimensões

Nós só aprenderemos os conceitos básicos do NumPy, para começar, precisamos instalá-lo!


Documentação http://www.numpy.org/

## Instruções de instalação

**É altamente recomendável que instale o Python usando a distribuição da Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de Álgebra Linear) se sincronizem com o uso de uma instalação conda. Se você tiver o Anaconda, instale o NumPy acessando seu terminal ou prompt de comando e digite:**

    conda install numpy
    
**Se você não possui Anaconda e não pode instalá-lo, consulte: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

**Uma  outra maneira seria:**

     pip install numpy

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
! pip install numpy

In [2]:
import numpy as np

Numpy possui muitas funções e capacidades incorporadas. Não vamos cobri-los na totalidade, mas, em vez disso, vamos nos concentrar em alguns dos aspectos mais importantes de Numpy: vetores, arrays, matrizes e geração de números. Comecemos por arrays:

# Numpy Arrays

As matrizes de NumPy são a maneira principal de usar Numpy ao longo do curso. Numpy arrays essencialmente vêm de duas formas: vetores e matrizes. Os vetores são estritamente arranjos de 1d e as matrizes são 2d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [3]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista)

array([1, 2, 3])

In [6]:
#ajuda sobre método array
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [7]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [20]:
np.linspace(0,15,10)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [27]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [23]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [23]:
np.random.rand(10)

array([0.05433412, 0.04282232, 0.66319368, 0.25319952, 0.14984427,
       0.79899716, 0.73394119, 0.59332609, 0.21722513, 0.58451718])

In [24]:
np.random.rand(5,5)

array([[0.12879967, 0.05911533, 0.43102758, 0.90428225, 0.30601272],
       [0.55756622, 0.12161509, 0.20602366, 0.78184607, 0.62690023],
       [0.39880371, 0.0228613 , 0.15959866, 0.17124728, 0.5749405 ],
       [0.54710127, 0.26275848, 0.37774547, 0.89584975, 0.28877277],
       [0.68539698, 0.12533558, 0.86692709, 0.72052606, 0.74687605]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [26]:
np.random.randn(10)

array([ 1.3801869 , -0.62297618,  0.65319924,  2.06789062, -0.50082772,
        0.37927877,  0.44374748,  1.10015933,  0.9190434 ,  0.63781522])

In [32]:
np.random.randn(15,15)

array([[ 1.71990103,  0.36669071, -1.99877186, -0.90241617, -1.86537951,
         0.51859695,  1.60941764,  0.18515368, -1.11624556, -0.64876229,
        -0.87944882, -0.07903151, -0.32345845,  0.95050741,  1.18116359],
       [ 0.36513313,  0.20190523,  0.90742698, -0.02408943,  0.22945923,
         1.89026523, -1.26964552, -0.5178683 ,  1.10192043,  0.05004836,
         0.67917224,  0.49531885, -0.30725487,  1.91709952,  0.24073719],
       [ 1.6002145 ,  0.45770073,  0.4951442 ,  1.29718218,  0.77059584,
        -0.92020983,  0.30648475,  0.81550406, -2.0643708 ,  1.2587778 ,
         0.25959845,  0.54011327, -0.20313925,  0.75703312, -1.90596466],
       [ 0.9919779 , -1.27951128,  0.65542832, -0.22269404,  0.59974141,
        -0.209474  ,  2.39179768,  1.82002788,  1.31931191,  2.5223803 ,
         0.36066713,  0.84717692,  0.02803993,  0.53365722, -0.55107568],
       [ 0.50989974, -0.89072565,  0.45036924,  0.29916769,  0.69435947,
        -1.2504324 , -0.74477674, -1.09525242, 

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [31]:
np.random.randint(1,10000)

7510

In [30]:
np.random.randint(1,100,1)

array([47])

In [33]:
np.random.randint(1,100,10)

array([25, 42, 89, 34, 64, 84, 38, 69, 68, 37])

In [34]:
np.random.randint(1,100,10)

array([95, 65, 37, 33, 60, 45, 10, 80, 14,  6])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [36]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
ranarr

array([ 8, 37,  1, 43,  0, 48, 33, 22,  4, 47])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [42]:
ranarr

array([ 0, 15, 34, 40, 30, 22,  2, 15, 22, 44])

In [40]:
ranarr.max()

44

In [43]:
ranarr.argmax()

9

In [44]:
ranarr.min()

0

In [45]:
ranarr.argmin()

0

In [85]:
help(ranarr.argmin)

Help on built-in function argmin:

argmin(...) method of numpy.ndarray instance
    a.argmin(axis=None, out=None)
    
    Return indices of the minimum values along the given axis of `a`.
    
    Refer to `numpy.argmin` for detailed documentation.
    
    See Also
    --------
    numpy.argmin : equivalent function



## Shape

Shape é um atributo que os arrays têm (não um método):

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
# Vector
arr.shape

(25,)

In [47]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [86]:
arr.reshape(1,25).shape

(1, 25)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [97]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [88]:
arr.dtype

dtype('int32')