# Pré processamento de dados

# Importação das bibliotecas básicas

In [1]:
import pandas as pd
import numpy as np

### Exploração dos dados

In [2]:
from google.colab import files
uploaded = files.upload()

Saving census.csv to census.csv


In [3]:
base_census = pd.read_csv('census.csv')

In [4]:
base_census

age          workclass  ...  native-country  income
0       39          State-gov  ...   United-States   <=50K
1       50   Self-emp-not-inc  ...   United-States   <=50K
2       38            Private  ...   United-States   <=50K
3       53            Private  ...   United-States   <=50K
4       28            Private  ...            Cuba   <=50K
...    ...                ...  ...             ...     ...
32556   27            Private  ...   United-States   <=50K
32557   40            Private  ...   United-States    >50K
32558   58            Private  ...   United-States   <=50K
32559   22            Private  ...   United-States   <=50K
32560   52       Self-emp-inc  ...   United-States    >50K

[32561 rows x 15 columns]

In [5]:
base_census.describe()

age  final-weight  ...  capital-loos  hour-per-week
count  32561.000000  3.256100e+04  ...  32561.000000   32561.000000
mean      38.581647  1.897784e+05  ...     87.303830      40.437456
std       13.640433  1.055500e+05  ...    402.960219      12.347429
min       17.000000  1.228500e+04  ...      0.000000       1.000000
25%       28.000000  1.178270e+05  ...      0.000000      40.000000
50%       37.000000  1.783560e+05  ...      0.000000      40.000000
75%       48.000000  2.370510e+05  ...      0.000000      45.000000
max       90.000000  1.484705e+06  ...   4356.000000      99.000000

[8 rows x 6 columns]

In [6]:
base_census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   final-weight    32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loos    32561 non-null  int64 
 12  hour-per-week   32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [9]:
base_census.isnull().sum()
base_census.isna().sum()

age               0
workclass         0
final-weight      0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loos      0
hour-per-week     0
native-country    0
income            0
dtype: int64

## Divisão entre previsores e classe

In [13]:
base_census.columns.sum()

AttributeError: ignored

In [31]:
X_census = base_census.iloc[:, 0:14].values

In [22]:
type(X_census)

numpy.ndarray

In [23]:
y_census = base_census.iloc[:,14].values

In [18]:
type(y_census)

pandas.core.series.Series

## Tratamento de atributos categóricos

### LabelEncoder

In [24]:
base_census.head(10)

age          workclass  final-weight  ... hour-per-week  native-country  income
0   39          State-gov         77516  ...            40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...            13   United-States   <=50K
2   38            Private        215646  ...            40   United-States   <=50K
3   53            Private        234721  ...            40   United-States   <=50K
4   28            Private        338409  ...            40            Cuba   <=50K
5   37            Private        284582  ...            40   United-States   <=50K
6   49            Private        160187  ...            16         Jamaica   <=50K
7   52   Self-emp-not-inc        209642  ...            45   United-States    >50K
8   31            Private         45781  ...            50   United-States    >50K
9   42            Private        159449  ...            40   United-States    >50K

[10 rows x 15 columns]

In [32]:
from sklearn.preprocessing import LabelEncoder
le_teste = LabelEncoder()


In [33]:
X_census[:,1]

array([' State-gov', ' Self-emp-not-inc', ' Private', ..., ' Private',
       ' Private', ' Self-emp-inc'], dtype=object)

In [27]:
teste = le_teste.fit_transform(X_census[:,1])

In [28]:
teste

array([7, 6, 4, ..., 4, 4, 5])

In [ ]:
X_census[0]

In [36]:
le_workclass = LabelEncoder()
le_education = LabelEncoder()
le_marital = LabelEncoder
le_occupation = LabelEncoder()
le_relationship = LabelEncoder()
le_race = LabelEncoder()
le_sex = LabelEncoder()
le_country = LabelEncoder()

In [37]:
X_census[:,1] = le_workclass.fit_transform(X_census[:,1])
X_census[:,3] = le_workclass.fit_transform(X_census[:,3])
X_census[:,5] = le_workclass.fit_transform(X_census[:,5])
X_census[:,6] = le_workclass.fit_transform(X_census[:,6])
X_census[:,7] = le_workclass.fit_transform(X_census[:,7])
X_census[:,8] = le_workclass.fit_transform(X_census[:,8])
X_census[:,9] = le_workclass.fit_transform(X_census[:,9])
X_census[:,13] = le_workclass.fit_transform(X_census[:,13])

In [40]:
X_census[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

In [42]:
X_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

### OneHotEncoder

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
enc = OneHotEncoder()

In [82]:
x = base_census.loc[:,['workclass','education','occupation']]

In [83]:
df = pd.DataFrame(data = x)
df

workclass    education          occupation
0              State-gov    Bachelors        Adm-clerical
1       Self-emp-not-inc    Bachelors     Exec-managerial
2                Private      HS-grad   Handlers-cleaners
3                Private         11th   Handlers-cleaners
4                Private    Bachelors      Prof-specialty
...                  ...          ...                 ...
32556            Private   Assoc-acdm        Tech-support
32557            Private      HS-grad   Machine-op-inspct
32558            Private      HS-grad        Adm-clerical
32559            Private      HS-grad        Adm-clerical
32560       Self-emp-inc      HS-grad     Exec-managerial

[32561 rows x 3 columns]

In [48]:
len(np.unique(df['workclass']))

9

In [49]:
len(np.unique(df['education']))

16

In [50]:
len(np.unique(df['occupation']))

15

In [58]:
df.drop(df.index[10:], inplace=True)

In [65]:
df

workclass    education          occupation
0              State-gov    Bachelors        Adm-clerical
1       Self-emp-not-inc    Bachelors     Exec-managerial
2                Private      HS-grad   Handlers-cleaners
3                Private         11th   Handlers-cleaners
4                Private    Bachelors      Prof-specialty
...                  ...          ...                 ...
32556            Private   Assoc-acdm        Tech-support
32557            Private      HS-grad   Machine-op-inspct
32558            Private      HS-grad        Adm-clerical
32559            Private      HS-grad        Adm-clerical
32560       Self-emp-inc      HS-grad     Exec-managerial

[32561 rows x 3 columns]

In [66]:
df = enc.fit_transform(df).toarray()

In [67]:
df

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
df.shape

(32561, 40)

In [71]:
df2 = pd.get_dummies(base_census['sex'], drop_first= True)

In [72]:
df2

Male
0          1
1          1
2          1
3          1
4          0
...      ...
32556      0
32557      1
32558      0
32559      1
32560      0

[32561 rows x 1 columns]

## Escalonamento dos valores

##### Standard Scaler


In [73]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()

In [76]:
 X_census = scaler_census.fit_transform(X_census)

In [78]:
X_census

array([[ 0.03067056,  2.15057856, -1.06361075, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [ 0.83710898,  1.46373585, -1.008707  , ..., -0.21665953,
        -2.22215312,  0.29156857],
       [-0.04264203,  0.09005041,  0.2450785 , ..., -0.21665953,
        -0.03542945,  0.29156857],
       ...,
       [ 1.42360965,  0.09005041, -0.35877741, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [-1.21564337,  0.09005041,  0.11095988, ..., -0.21665953,
        -1.65522476,  0.29156857],
       [ 0.98373415,  0.77689313,  0.92989258, ..., -0.21665953,
        -0.03542945,  0.29156857]])


##### Normalize

In [79]:
from sklearn.preprocessing import MinMaxScaler
nM = MinMaxScaler()

In [84]:
data = nM.fit_transform(df)

ValueError: ignored

In [85]:
data = nM.fit_transform(X_census)

In [86]:
data

array([[0.30136986, 0.875     , 0.0443019 , ..., 0.        , 0.39795918,
        0.95121951],
       [0.45205479, 0.75      , 0.0482376 , ..., 0.        , 0.12244898,
        0.95121951],
       [0.28767123, 0.5       , 0.13811345, ..., 0.        , 0.39795918,
        0.95121951],
       ...,
       [0.56164384, 0.5       , 0.09482688, ..., 0.        , 0.39795918,
        0.95121951],
       [0.06849315, 0.5       , 0.12849934, ..., 0.        , 0.19387755,
        0.95121951],
       [0.47945205, 0.625     , 0.18720338, ..., 0.        , 0.39795918,
        0.95121951]])